/**
 * yarn (v1 + Berry) and pnpm (v5/v6/v9) lockfiles: dev/prod + direct/transitive
 * classification must come from the dependency GRAPH walked from the package.json
 * roots — the same contract the package-lock path honours.
 *
 * Before the fix every yarn entry was emitted `scope:"prod", depth:0` with no isDev,
 * so a devDependency (and everything it pulls in) was gated as production, and every
 * transitive was reported as a direct dep. pnpm got direct dev right but turned every
 * transitive of a dev dep into prod, and every transitive into a "direct".
 *
 * One graph, written in every format:
 *
 *   package.json  dependencies:    app-prod ^1.0.0
 *                 devDependencies: jest-fake 1.0.0
 *
 *   app-prod@1.2.0  → shared@1.0.0, ms@2.1.3
 *   jest-fake@1.0.0 → lodash@4.17.15, shared@1.0.0, ms@1.0.0
 *   lodash@4.17.15  → deep@1.0.1
 *   orphan-pkg@1.0.0   (in the lock, reachable from nothing)
 *
 * Expected:
 *   app-prod   prod        depth 0  isDev false
 *   jest-fake  dev         depth 0  isDev true
 *   lodash     transitive  depth 1  isDev true   via [npm:jest-fake]
 *   deep       transitive  depth 2  isDev true   via [npm:jest-fake, npm:lodash]
 *   shared     transitive  depth 1  isDev false  (reachable from BOTH → prod), via the prod root
 *   ms@2.1.3   transitive           isDev false
 *   ms@1.0.0   transitive           isDev true   (same name, other version, dev-only)
 *   orphan-pkg transitive           isDev false  (never invented as a prod DIRECT)
 */
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const os = require("os");
const path = require("path");

const { parseYarnLockV1, parsePnpmLock } = require("../lib/codecs/npm/parse");
const { collectNpmDeps } = require("../lib/codecs/npm/collect");
const { attributeMatchOrigins } = require("../lib/attribution");

const PKG = { name: "app", version: "1.0.0", dependencies: { "app-prod": "^1.0.0" }, devDependencies: { "jest-fake": "1.0.0" } };

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"app-prod@^1.0.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/app-prod/-/app-prod-1.2.0.tgz"
  dependencies:
    ms "^2.1.0"
    shared "^1.0.0"

deep@^1.0.0:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/deep/-/deep-1.0.1.tgz"

"jest-fake@1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/jest-fake/-/jest-fake-1.0.0.tgz"
  dependencies:
    lodash "4.17.15"
    ms "1.0.0"
    shared "^1.0.0"

lodash@4.17.15:
  version "4.17.15"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz"
  dependencies:
    deep "^1.0.0"

ms@1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/ms/-/ms-1.0.0.tgz"

ms@^2.1.0:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz"

orphan-pkg@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/orphan-pkg/-/orphan-pkg-1.0.0.tgz"

shared@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/shared/-/shared-1.0.0.tgz"
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"app-prod@npm:^1.0.0":
  version: 1.2.0
  resolution: "app-prod@npm:1.2.0"
  dependencies:
    ms: "npm:^2.1.0"
    shared: "npm:^1.0.0"
  checksum: 10c0/a
  languageName: node
  linkType: hard

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  dependencies:
    app-prod: "npm:^1.0.0"
    jest-fake: "npm:1.0.0"
  languageName: unknown
  linkType: soft

"deep@npm:^1.0.0":
  version: 1.0.1
  resolution: "deep@npm:1.0.1"
  checksum: 10c0/b
  languageName: node
  linkType: hard

"jest-fake@npm:1.0.0":
  version: 1.0.0
  resolution: "jest-fake@npm:1.0.0"
  dependencies:
    lodash: "npm:4.17.15"
    ms: "npm:1.0.0"
    shared: "npm:^1.0.0"
  checksum: 10c0/c
  languageName: node
  linkType: hard

"lodash@npm:4.17.15":
  version: 4.17.15
  resolution: "lodash@npm:4.17.15"
  dependencies:
    deep: "npm:^1.0.0"
  checksum: 10c0/d
  languageName: node
  linkType: hard

"ms@npm:1.0.0":
  version: 1.0.0
  resolution: "ms@npm:1.0.0"
  checksum: 10c0/e
  languageName: node
  linkType: hard

"ms@npm:^2.1.0":
  version: 2.1.3
  resolution: "ms@npm:2.1.3"
  checksum: 10c0/f
  languageName: node
  linkType: hard

"orphan-pkg@npm:^1.0.0":
  version: 1.0.0
  resolution: "orphan-pkg@npm:1.0.0"
  checksum: 10c0/g
  languageName: node
  linkType: hard

"shared@npm:^1.0.0":
  version: 1.0.0
  resolution: "shared@npm:1.0.0"
  checksum: 10c0/h
  languageName: node
  linkType: hard
`;

const PNPM_V9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      app-prod:
        specifier: ^1.0.0
        version: 1.2.0
    devDependencies:
      jest-fake:
        specifier: 1.0.0
        version: 1.0.0

packages:

  app-prod@1.2.0:
    resolution: {integrity: sha512-a}
  deep@1.0.1:
    resolution: {integrity: sha512-b}
  jest-fake@1.0.0:
    resolution: {integrity: sha512-c}
  lodash@4.17.15:
    resolution: {integrity: sha512-d}
  ms@1.0.0:
    resolution: {integrity: sha512-e}
  ms@2.1.3:
    resolution: {integrity: sha512-f}
  orphan-pkg@1.0.0:
    resolution: {integrity: sha512-g}
  shared@1.0.0:
    resolution: {integrity: sha512-h}

snapshots:

  app-prod@1.2.0:
    dependencies:
      ms: 2.1.3
      shared: 1.0.0
  deep@1.0.1: {}
  jest-fake@1.0.0:
    dependencies:
      lodash: 4.17.15
      ms: 1.0.0
      shared: 1.0.0
  lodash@4.17.15:
    dependencies:
      deep: 1.0.1
  ms@1.0.0: {}
  ms@2.1.3: {}
  orphan-pkg@1.0.0: {}
  shared@1.0.0: {}
`;

// v6 carries pnpm's own `dev:` flag — deliberately set WRONG on lodash here (false)
// so the test proves the classification comes from the graph, not the flag.
const PNPM_V6 = `lockfileVersion: '6.0'

dependencies:
  app-prod:
    specifier: ^1.0.0
    version: 1.2.0

devDependencies:
  jest-fake:
    specifier: 1.0.0
    version: 1.0.0

packages:

  /app-prod@1.2.0:
    resolution: {integrity: sha512-a}
    dependencies:
      ms: 2.1.3
      shared: 1.0.0
    dev: false

  /deep@1.0.1:
    resolution: {integrity: sha512-b}
    dev: true

  /jest-fake@1.0.0:
    resolution: {integrity: sha512-c}
    dependencies:
      lodash: 4.17.15
      ms: 1.0.0
      shared: 1.0.0
    dev: true

  /lodash@4.17.15:
    resolution: {integrity: sha512-d}
    dependencies:
      deep: 1.0.1
    dev: false

  /ms@1.0.0:
    resolution: {integrity: sha512-e}
    dev: true

  /ms@2.1.3:
    resolution: {integrity: sha512-f}
    dev: false

  /orphan-pkg@1.0.0:
    resolution: {integrity: sha512-g}
    dev: false

  /shared@1.0.0:
    resolution: {integrity: sha512-h}
`;

const PNPM_V5 = `lockfileVersion: 5.4

specifiers:
  app-prod: ^1.0.0
  jest-fake: 1.0.0

dependencies:
  app-prod: 1.2.0

devDependencies:
  jest-fake: 1.0.0

packages:

  /app-prod/1.2.0:
    resolution: {integrity: sha512-a}
    dependencies:
      ms: 2.1.3
      shared: 1.0.0
    dev: false

  /deep/1.0.1:
    resolution: {integrity: sha512-b}
    dev: true

  /jest-fake/1.0.0:
    resolution: {integrity: sha512-c}
    dependencies:
      lodash: 4.17.15
      ms: 1.0.0
      shared: 1.0.0
    dev: true

  /lodash/4.17.15:
    resolution: {integrity: sha512-d}
    dependencies:
      deep: 1.0.1
    dev: true

  /ms/1.0.0:
    resolution: {integrity: sha512-e}
    dev: true

  /ms/2.1.3:
    resolution: {integrity: sha512-f}
    dev: false

  /orphan-pkg/1.0.0:
    resolution: {integrity: sha512-g}
    dev: false

  /shared/1.0.0:
    resolution: {integrity: sha512-h}
`;

function project(lockName, lockBody, pkg = PKG) {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "fad-npm-graph-"));
	fs.writeFileSync(path.join(dir, "package.json"), JSON.stringify(pkg));
	fs.writeFileSync(path.join(dir, lockName), lockBody);
	return dir;
}

function byNameVersion(deps) {
	const out = {};
	for (const d of deps) out[`${d.name}@${d.version}`] = d;
	return out;
}

/** The parse-level contract every format must meet on the shared graph. */
function assertGraph(deps, label) {
	const m = byNameVersion(deps);
	const get = k => { assert.ok(m[k], `${label}: ${k} missing (have ${Object.keys(m).join(", ")})`); return m[k]; };

	const appProd = get("app-prod@1.2.0");
	assert.equal(appProd.scope, "prod", `${label}: app-prod scope`);
	assert.equal(appProd.depth, 0, `${label}: app-prod depth`);
	assert.equal(appProd.isDev, false, `${label}: app-prod isDev`);

	const jest = get("jest-fake@1.0.0");
	assert.equal(jest.scope, "dev", `${label}: jest-fake scope`);
	assert.equal(jest.depth, 0, `${label}: jest-fake depth`);
	assert.equal(jest.isDev, true, `${label}: a direct devDependency is dev`);

	const lodash = get("lodash@4.17.15");
	assert.equal(lodash.scope, "transitive", `${label}: lodash is a transitive, not a direct`);
	assert.equal(lodash.depth, 1, `${label}: lodash depth`);
	assert.equal(lodash.isDev, true, `${label}: a transitive of a dev-only root is dev`);
	assert.deepEqual(lodash.via, ["npm:jest-fake"], `${label}: lodash via`);

	const deep = get("deep@1.0.1");
	assert.equal(deep.scope, "transitive", `${label}: deep scope`);
	assert.equal(deep.depth, 2, `${label}: deep depth`);
	assert.equal(deep.isDev, true, `${label}: deep isDev`);
	assert.deepEqual(deep.via, ["npm:jest-fake", "npm:lodash"], `${label}: deep via`);

	const shared = get("shared@1.0.0");
	assert.equal(shared.scope, "transitive", `${label}: shared scope`);
	assert.equal(shared.isDev, false, `${label}: reachable from a prod root AND a dev root → prod`);
	assert.deepEqual(shared.via, ["npm:app-prod"], `${label}: the chain shown is the PRODUCTION one`);

	assert.equal(get("ms@2.1.3").isDev, false, `${label}: ms@2.1.3 (prod path) isDev`);
	assert.equal(get("ms@2.1.3").scope, "transitive", `${label}: ms@2.1.3 scope`);
	assert.equal(get("ms@1.0.0").isDev, true, `${label}: ms@1.0.0 (dev-only path) isDev`);
	assert.equal(get("ms@1.0.0").scope, "transitive", `${label}: ms@1.0.0 scope`);

	const orphan = get("orphan-pkg@1.0.0");
	assert.equal(orphan.scope, "transitive", `${label}: an orphan is never invented as a direct prod dep`);
	assert.equal(orphan.isDev, false, `${label}: orphan isDev mirrors the package-lock path (lock flag, else false)`);
}

test("yarn v1: dev/prod + direct/transitive classified from the package.json roots", () => {
	const dir = project("yarn.lock", YARN_V1);
	assertGraph(parseYarnLockV1(path.join(dir, "yarn.lock")).deps, "yarn-v1");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("yarn Berry: dev/prod + direct/transitive classified from the package.json roots", () => {
	const dir = project("yarn.lock", YARN_BERRY);
	const r = parseYarnLockV1(path.join(dir, "yarn.lock"));
	assert.equal(r.lockfileVersion, "berry");
	assertGraph(r.deps, "yarn-berry");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("pnpm v9: transitives of a dev root are dev, every transitive is a transitive", () => {
	const dir = project("pnpm-lock.yaml", PNPM_V9);
	assertGraph(parsePnpmLock(path.join(dir, "pnpm-lock.yaml")).deps, "pnpm-v9");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("pnpm v6: graph walk wins over a stale dev flag", () => {
	const dir = project("pnpm-lock.yaml", PNPM_V6);
	assertGraph(parsePnpmLock(path.join(dir, "pnpm-lock.yaml")).deps, "pnpm-v6");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("pnpm v5: slash-form keys walked the same way", () => {
	const dir = project("pnpm-lock.yaml", PNPM_V5);
	assertGraph(parsePnpmLock(path.join(dir, "pnpm-lock.yaml")).deps, "pnpm-v5");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("pnpm v5: a peer-suffixed key (/name/1.0.0_react@18.0.0) keeps the real name and version", () => {
	const lock = `lockfileVersion: 5.4

dependencies:
  peerful: 1.0.0_react@18.0.0

packages:

  /peerful/1.0.0_react@18.0.0:
    resolution: {integrity: sha512-a}
    dependencies:
      react: 18.0.0
    dev: false

  /react/18.0.0:
    resolution: {integrity: sha512-b}
    dev: false
`;
	const dir = project("pnpm-lock.yaml", lock, { name: "p", dependencies: { peerful: "1.0.0" } });
	const m = byNameVersion(parsePnpmLock(path.join(dir, "pnpm-lock.yaml")).deps);
	assert.ok(m["peerful@1.0.0"], `peerful parsed (have ${Object.keys(m).join(", ")})`);
	assert.equal(m["peerful@1.0.0"].scope, "prod");
	assert.equal(m["react@18.0.0"].scope, "transitive");
	assert.deepEqual(m["react@18.0.0"].via, ["npm:peerful"]);
	fs.rmSync(dir, { recursive: true, force: true });
});

test("yarn v1 audit repro: direct devDependency + its transitive are dev, not gated as production", () => {
	const lock = `# yarn lockfile v1


"jest-fake@1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/jest-fake/-/jest-fake-1.0.0.tgz"
  dependencies:
    lodash "4.17.15"

"lodash@4.17.15":
  version "4.17.15"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz"

"ms@2.1.3":
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz"
`;
	const dir = project("yarn.lock", lock, { name: "yarntest", version: "1.0.0", dependencies: { ms: "2.1.3" }, devDependencies: { "jest-fake": "1.0.0" } });
	const map = collectNpmDeps(dir);
	assert.equal(map.get("npm:jest-fake").scope, "dev");
	assert.equal(map.get("npm:jest-fake").isDev, true, "direct dev dep must not be gated as production");
	assert.equal(map.get("npm:lodash").scope, "transitive");
	assert.equal(map.get("npm:lodash").isDev, true, "transitive of a dev dep must not be gated as production");
	assert.deepEqual(map.get("npm:lodash").via, ["npm:jest-fake"]);
	assert.equal(map.get("npm:ms").scope, "prod");
	assert.equal(map.get("npm:ms").isDev, false);
	fs.rmSync(dir, { recursive: true, force: true });
});

test("collectNpmDeps (yarn v1 / Berry / pnpm): record shape matches the package-lock path", () => {
	for (const [lockName, body, lockType] of [["yarn.lock", YARN_V1, "yarn-v1"], ["yarn.lock", YARN_BERRY, "yarn-berry"], ["pnpm-lock.yaml", PNPM_V9, "pnpm"]]) {
		const dir = project(lockName, body);
		const map = collectNpmDeps(dir);
		const lodash = map.get("npm:lodash");
		assert.equal(lodash.lockType, lockType);
		assert.equal(lodash.scope, "transitive", `${lockType}: lodash scope`);
		assert.equal(lodash.isDev, true, `${lockType}: lodash isDev`);
		assert.equal(lodash.depth, 1, `${lockType}: lodash depth`);
		assert.deepEqual(lodash.via, ["npm:jest-fake"], `${lockType}: lodash via`);
		assert.deepEqual(lodash.viaPaths, [["npm:jest-fake"]], `${lockType}: lodash viaPaths`);
		assert.equal(map.get("npm:jest-fake").isDev, true, `${lockType}: jest-fake isDev`);
		assert.equal(map.get("npm:jest-fake").via, undefined, `${lockType}: a direct dep carries no via chain`);
		assert.equal(map.get("npm:shared").isDev, false, `${lockType}: shared isDev`);
		assert.equal(map.get("npm:app-prod").scope, "prod", `${lockType}: app-prod scope`);
		assert.equal(map.get("npm:orphan-pkg").scope, "transitive", `${lockType}: orphan scope`);
		// Coord-wide record: ms is prod overall (one version is), but each version keeps
		// its own classification for lib/attribution.js.
		const ms = map.get("npm:ms");
		assert.deepEqual([...ms.versions].sort(), ["1.0.0", "2.1.3"]);
		assert.equal(ms.isDev, false);
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("per-version classification reaches the match: ms@1.0.0 (dev-only) is dev, ms@2.1.3 is prod", () => {
	const dir = project("yarn.lock", YARN_V1);
	const map = collectNpmDeps(dir);
	const ms = map.get("npm:ms");
	// matchOne clones the coord-wide record per version; attribution re-stamps it.
	const matches = ["1.0.0", "2.1.3"].map(v => ({ dep: { ...ms, version: v }, cve: { id: `CVE-X-${v}` } }));
	attributeMatchOrigins(matches);
	assert.equal(matches[0].dep.isDev, true, "ms@1.0.0 is reachable only through jest-fake");
	assert.equal(matches[1].dep.isDev, false, "ms@2.1.3 is reachable through app-prod");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("--ignore-test drops dev-only transitives too, keeps a dep reachable from prod", () => {
	for (const [lockName, body] of [["yarn.lock", YARN_V1], ["yarn.lock", YARN_BERRY], ["pnpm-lock.yaml", PNPM_V9]]) {
		const dir = project(lockName, body);
		const map = collectNpmDeps(dir, { ignoreTest: true });
		assert.equal(map.has("npm:jest-fake"), false, `${lockName}: direct dev dropped`);
		assert.equal(map.has("npm:lodash"), false, `${lockName}: dev-only transitive dropped`);
		assert.equal(map.has("npm:deep"), false, `${lockName}: dev-only transitive (depth 2) dropped`);
		assert.equal(map.has("npm:shared"), true, `${lockName}: shared is reachable from prod`);
		assert.deepEqual(map.get("npm:ms").versions, ["2.1.3"], `${lockName}: only the prod version of ms survives`);
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

test("a direct devDependency also pulled in by a prod dep is NOT dev", () => {
	const lock = `# yarn lockfile v1


a@1.0.0:
  version "1.0.0"
  dependencies:
    b "1.0.0"

b@1.0.0:
  version "1.0.0"
`;
	const dir = project("yarn.lock", lock, { name: "x", dependencies: { a: "1.0.0" }, devDependencies: { b: "1.0.0" } });
	const m = byNameVersion(parseYarnLockV1(path.join(dir, "yarn.lock")).deps);
	assert.equal(m["b@1.0.0"].scope, "dev", "declared as a devDependency → direct dev scope");
	assert.equal(m["b@1.0.0"].depth, 0);
	assert.equal(m["b@1.0.0"].isDev, false, "but it ships with a, so it is production");
	fs.rmSync(dir, { recursive: true, force: true });
});

test("yarn v1 workspaces: members' package.json files are roots too", () => {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "fad-npm-ws-"));
	fs.writeFileSync(path.join(dir, "package.json"), JSON.stringify({ name: "root", private: true, workspaces: ["packages/*"], devDependencies: { tooling: "1.0.0" } }));
	fs.mkdirSync(path.join(dir, "packages", "web"), { recursive: true });
	fs.writeFileSync(path.join(dir, "packages", "web", "package.json"), JSON.stringify({ name: "web", dependencies: { express: "^4.0.0" }, devDependencies: { mocha: "9.0.0" } }));
	fs.writeFileSync(path.join(dir, "yarn.lock"), `# yarn lockfile v1


express@^4.0.0:
  version "4.18.0"
  dependencies:
    qs "6.11.0"

mocha@9.0.0:
  version "9.0.0"

qs@6.11.0:
  version "6.11.0"

tooling@1.0.0:
  version "1.0.0"
`);
	const m = byNameVersion(parseYarnLockV1(path.join(dir, "yarn.lock")).deps);
	assert.equal(m["express@4.18.0"].scope, "prod");
	assert.equal(m["express@4.18.0"].isDev, false);
	assert.equal(m["qs@6.11.0"].scope, "transitive");
	assert.deepEqual(m["qs@6.11.0"].via, ["npm:express"]);
	assert.equal(m["mocha@9.0.0"].isDev, true);
	assert.equal(m["tooling@1.0.0"].isDev, true);
	fs.rmSync(dir, { recursive: true, force: true });
});

test("fixtures: yarn-berry jest is dev, @babel/types is a transitive of @babel/core", () => {
	const r = parseYarnLockV1(path.join(__dirname, "fixtures", "yarn-berry", "yarn.lock"));
	const m = Object.fromEntries(r.deps.map(d => [d.name, d]));
	assert.equal(m.jest.isDev, true);
	assert.equal(m.jest.scope, "dev");
	assert.equal(m["@babel/types"].scope, "transitive");
	assert.deepEqual(m["@babel/types"].via, ["npm:@babel/core"]);
	assert.equal(m["@babel/types"].isDev, false);
	assert.equal(m.lodash.scope, "prod");
});

test("fixtures: monorepo-mixed yarn v1 — mocha dev, chalk's deps transitive", () => {
	const r = parseYarnLockV1(path.join(__dirname, "fixtures", "monorepo-mixed", "packages", "cli", "yarn.lock"));
	const m = Object.fromEntries(r.deps.map(d => [d.name, d]));
	assert.equal(m.mocha.isDev, true);
	assert.equal(m.chalk.scope, "prod");
	assert.equal(m["ansi-styles"].scope, "transitive");
	assert.deepEqual(m["ansi-styles"].via, ["npm:chalk"]);
	assert.equal(m["ansi-styles"].isDev, false);
});
