/**
 * lib/outdated.js — EOL, obsolete, and outdated dependency checks.
 *
 * EOL data comes from endoflife.date (with on-disk cache).
 * Obsolete data is curated locally (data/known-obsolete.json).
 * Outdated comes from Maven Central's maven-metadata.xml.
 *
 * @author: N.BRAUN
 * @email: pp9ping@gmail.com
 */
const fs = require("fs");
const path = require("path");
const os = require("os");
const { compareMavenVersions, latestStableVersion } = require("./maven-version");
const { webjarToNpm } = require("./codecs/npm/collect");

const KNOWN_OBSOLETE = require("../data/known-obsolete.json");
const EOL_MAPPING = require("../data/eol-mapping.json");

// Generated by scripts/gen-composer-eol-map.js — Composer packages versioned in lockstep with
// their framework (the monorepo's `replace: self.version` table). A package on its own version
// line (monolog-bundle, *-contracts, polyfill-*, flex …) is deliberately ABSENT: mapping it to
// the framework's endoflife cycles would be a false positive.
const COMPOSER_FRAMEWORKS = require("../data/eol-composer-frameworks.json");
const COMPOSER_FRAMEWORK_OF = new Map();
for (const [id, fw] of Object.entries(COMPOSER_FRAMEWORKS)) {
	for (const name of fw.components || []) COMPOSER_FRAMEWORK_OF.set(String(name).toLowerCase(), id);
}

const CACHE_DIR = path.join(os.homedir(), ".fad-checker");
const EOL_CACHE_PATH = path.join(CACHE_DIR, "eol-cache.json");
const VERSION_CACHE_PATH = path.join(CACHE_DIR, "version-cache.json");
const EOL_CACHE_MAX_AGE_MS = 7 * 24 * 3600 * 1000; // 7 days
const VERSION_CACHE_MAX_AGE_MS = 24 * 3600 * 1000; // 1 day

function loadJsonCache(file) {
	try { return JSON.parse(fs.readFileSync(file, "utf8")); }
	catch { return { meta: { fetchedAt: 0 }, entries: {} }; }
}

function saveJsonCache(file, data) {
	try {
		fs.mkdirSync(CACHE_DIR, { recursive: true });
		fs.writeFileSync(file, JSON.stringify(data));
	} catch { /* ignore */ }
}

function isEolCacheFresh(maxAge = EOL_CACHE_MAX_AGE_MS) {
	const c = loadJsonCache(EOL_CACHE_PATH);
	return c.meta?.fetchedAt && (Date.now() - c.meta.fetchedAt) < maxAge;
}

// -------- EOL via endoflife.date --------

// Tag the matched mapping entry with HOW it matched (which rule + which key), so
// the report can show where an EOL verdict comes from. Returns a COPY — the shared
// EOL_MAPPING objects must never be mutated (they're reused across deps).
function withOrigin(entry, via, viaKey) {
	return entry ? { ...entry, via, viaKey } : null;
}

function findEolProduct(dep) {
	// npm packages — and WebJars, which are client-side JS shipped as Maven
	// artifacts — resolve by JS library name, not Maven coordinate. npm deps
	// use their name directly; WebJars are reduced to their npm-equivalent name
	// first (org.webjars:angularjs → "angularjs", org.webjars.npm:angular__core
	// → "@angular/core"). The npm package literally named "angular" is AngularJS
	// 1.x; modern Angular is the @angular/* scope — hence the name vs. scope maps.
	const isWebjar = dep.ecosystem !== "npm" && webjarToNpm(dep) != null;
	const npmName = dep.ecosystem === "npm" ? (dep.artifactId || "") : webjarToNpm(dep)?.name;
	if (npmName != null) {
		const byName = EOL_MAPPING.by_npm_name?.[npmName];
		if (byName) return withOrigin(byName, isWebjar ? "webjar" : "npm-name", npmName);
		const scopes = Object.keys(EOL_MAPPING.by_npm_scope || {})
			.sort((a, b) => b.length - a.length);
		for (const s of scopes) {
			if (npmName.startsWith(s)) return withOrigin(EOL_MAPPING.by_npm_scope[s], isWebjar ? "webjar" : "npm-scope", s);
		}
		return null;
	}
	if (dep.ecosystem === "composer") {
		const full = `${dep.namespace || dep.groupId || ""}/${dep.name || dep.artifactId}`.toLowerCase();
		const frameworkId = COMPOSER_FRAMEWORK_OF.get(full);
		if (frameworkId) {
			const fw = COMPOSER_FRAMEWORKS[frameworkId];
			return { product: fw.product, label: fw.label, via: "composer-framework", viaKey: full, frameworkId };
		}
		return withOrigin(EOL_MAPPING.by_composer_name?.[full], "composer-name", full);
	}
	if (dep.ecosystem === "pypi") {
		const k = (dep.name || dep.artifactId || "").toLowerCase();
		return withOrigin(EOL_MAPPING.by_pypi_name?.[k], "pypi-name", k);
	}
	if (dep.ecosystem === "nuget") {
		const k = (dep.name || dep.artifactId || "").toLowerCase();
		return withOrigin(EOL_MAPPING.by_nuget_name?.[k], "nuget-name", k);
	}
	const key = `${dep.groupId}:${dep.artifactId}`;
	const direct = EOL_MAPPING.by_group_artifact?.[key];
	if (direct) return withOrigin(direct, "group-artifact", key);
	// Match longest groupId prefix
	const prefixes = Object.keys(EOL_MAPPING.by_group_prefix || {})
		.sort((a, b) => b.length - a.length);
	for (const p of prefixes) {
		if (dep.groupId === p || dep.groupId.startsWith(p + ".")) {
			return withOrigin(EOL_MAPPING.by_group_prefix[p], "group-prefix", p);
		}
	}
	return null;
}

// Per-product freshness. `cache.fetchedAt[product]` is stamped on every SUCCESSFUL fetch;
// a legacy file (global stamp only) is normalised by normalizeEolCache() at load time.
function eolEntryFresh(cache, product, now = Date.now()) {
	const ts = cache.fetchedAt?.[product] ?? cache.meta?.fetchedAt ?? 0;
	return ts > 0 && (now - ts) < EOL_CACHE_MAX_AGE_MS;
}

/**
 * Bring an eol-cache.json body to the current shape without losing anything:
 *   { meta: { fetchedAt }, entries: { [product]: cycles[] | {error} }, fetchedAt: { [product]: ts } }
 * A file written before per-product stamps existed carries only meta.fetchedAt — give every
 * entry that global stamp ONCE, here, before any fetch in this run moves meta forward
 * (otherwise a refetch of product A would make untouched product B look fresh again).
 */
function normalizeEolCache(cache) {
	const c = cache && typeof cache === "object" ? cache : {};
	c.meta = c.meta && typeof c.meta === "object" ? c.meta : { fetchedAt: 0 };
	c.entries = c.entries && typeof c.entries === "object" ? c.entries : {};
	c.fetchedAt = c.fetchedAt && typeof c.fetchedAt === "object" ? c.fetchedAt : {};
	const legacy = Number(c.meta.fetchedAt) || 0;
	for (const product of Object.keys(c.entries)) if (c.fetchedAt[product] == null) c.fetchedAt[product] = legacy;
	return c;
}

function loadEolCache() {
	return normalizeEolCache(loadJsonCache(EOL_CACHE_PATH));
}

/**
 * Cycles for one endoflife.date product, cache-first.
 *   offline → the cached list regardless of age (air-gapped, the warmed cache is the only
 *             source: stale beats nothing, and we never block), else null.
 *   online  → the cached list while fresh (EOL_CACHE_MAX_AGE_MS, per product), otherwise a
 *             refetch. A failed refetch keeps serving the stale list; an {error} entry is
 *             never considered fresh, so it is retried on the next online run.
 * Only a SUCCESSFUL fetch stamps cache.fetchedAt[product] and meta.fetchedAt (the
 * provenance "data-source freshness") — a run that fetched nothing must not make the
 * cache look fresh. `opts.fetcher` / `opts.now` are injection points for tests.
 */
async function fetchEndoflife(product, cache, opts = {}) {
	const { offline = false, now = Date.now(), fetcher = globalThis.fetch } = opts;
	const cached = cache.entries[product];
	const usable = Array.isArray(cached);
	if (offline) return usable ? cached : null;
	if (usable && eolEntryFresh(cache, product, now)) return cached;
	try {
		const res = await fetcher(`https://endoflife.date/api/${encodeURIComponent(product)}.json`, {
			headers: { "User-Agent": "fad-checker-eol-checker" },
		});
		if (!res.ok) {
			if (usable) return cached;
			cache.entries[product] = { error: `HTTP ${res.status}` };
			return cache.entries[product];
		}
		const cycles = await res.json();
		cache.entries[product] = cycles;
		cache.fetchedAt = cache.fetchedAt || {};
		cache.fetchedAt[product] = now;
		cache.meta = { fetchedAt: now };
		return cycles;
	} catch (err) {
		if (usable) return cached;
		cache.entries[product] = { error: err.message };
		return cache.entries[product];
	}
}

/**
 * Cycles for ONE endoflife.date product, cache-first and offline-aware (a cold cache
 * offline → null, never a fabricated verdict). Persists the cache so a warmed online run
 * serves the air-gapped run. Used for products no dep maps to (the PHP runtime).
 */
async function getEolCycles(product, opts = {}) {
	const cache = loadEolCache();
	const cycles = await fetchEndoflife(product, cache, { offline: !!opts.offline });
	saveJsonCache(EOL_CACHE_PATH, cache);
	return Array.isArray(cycles) ? cycles : null;
}

function findCycleForVersion(cycles, version) {
	if (!Array.isArray(cycles) || !version) return null;
	// Match by cycle prefix: e.g. version "2.7.18" → cycle "2.7"
	for (const c of cycles) {
		const cycle = String(c.cycle || "");
		if (!cycle) continue;
		if (version === cycle || version.startsWith(cycle + ".") || version.startsWith(cycle + "-")) {
			return c;
		}
	}
	return null;
}

function isPastDate(v, now) {
	if (typeof v !== "string") return false;
	const t = Date.parse(v);
	return !Number.isNaN(t) && t < now;
}

/**
 * Lifecycle status of one endoflife.date cycle.
 *
 * The two fields have OPPOSITE boolean polarity: `eol: true` means the cycle IS
 * end-of-life, while `support: true` means it IS still actively supported. Both
 * may also be a "YYYY-MM-DD" date, compared against `now`.
 *
 *   "eol"         — no fixes of any kind any more
 *   "unsupported" — bug-fix (active) support ended, security fixes still provided
 *   "ok"          — actively supported, or no usable data (conservative)
 */
function lifecycleStatus(cycle, now = Date.now()) {
	if (!cycle) return "ok";
	if (cycle.eol === true || isPastDate(cycle.eol, now)) return "eol";
	if (cycle.support === false || isPastDate(cycle.support, now)) return "unsupported";
	return "ok";
}

function isEol(cycle) {
	return lifecycleStatus(cycle) === "eol";
}

/** One EOL finding. `dep` is the depRecord the report renders (for grouped framework
 *  findings, the ANCHOR dep — see groupFrameworkHits). `eol`/`support` are stringified
 *  ("true"/"false"/date) so exports and the report never see raw booleans. */
function makeEolFinding(dep, product, cycle, status) {
	const str = v => (v === true ? "true" : v === false ? "false" : v == null ? "" : String(v));
	return {
		dep,
		product: product.label || product.product,
		productSlug: product.product,
		via: product.via || null,
		viaKey: product.viaKey || null,
		frameworkId: product.frameworkId || null,
		cycle: str(cycle.cycle),
		status,
		eol: str(cycle.eol),
		support: str(cycle.support),
		latest: cycle.latest || null,
		notes: cycle.latestReleaseDate ? `Latest: ${cycle.latest} (${cycle.latestReleaseDate})` : "",
	};
}

/**
 * EOL check over the resolved deps.
 *   opts.eolSupport — also return "unsupported" findings (active support ended, security
 *                     fixes still provided). Off by default → output identical to before.
 *   opts.cycles     — { [productSlug]: cycles[] } injected for tests: bypasses the on-disk
 *                     cache AND the network entirely.
 *   opts.now        — clock override for tests.
 */
async function checkEolDeps(resolvedDeps, opts = {}) {
	const { verbose, offline, eolSupport = false, now = Date.now(), cycles: injected = null } = opts;
	const cache = injected ? normalizeEolCache({}) : loadEolCache();
	const seen = new Set();
	const plain = [];          // one finding per dep (Maven / npm / PyPI / NuGet / by_composer_name)
	const frameworkHits = [];  // Composer framework components → grouped per (framework, manifest, cycle)

	for (const dep of resolvedDeps.values()) {
		const product = findEolProduct(dep);
		if (!product) continue;
		const dedupeKey = `${dep.groupId}:${dep.artifactId}|${product.product}`;
		if (seen.has(dedupeKey)) continue;
		seen.add(dedupeKey);

		const cycles = injected
			? injected[product.product]
			: await fetchEndoflife(product.product, cache, { offline, now });

		if (!Array.isArray(cycles)) continue;
		const cycle = findCycleForVersion(cycles, dep.version);
		if (!cycle) continue;
		const status = lifecycleStatus(cycle, now);
		if (status === "ok") continue;
		if (status === "unsupported" && !eolSupport) continue;

		const hit = makeEolFinding(dep, product, cycle, status);
		if (product.frameworkId) frameworkHits.push(hit); else plain.push(hit);
		if (verbose) process.stdout.write(`  ${status.toUpperCase()}: ${dep.groupId}:${dep.artifactId}:${dep.version} (${product.label})\n`);
	}

	const results = groupEolByProduct(plain).concat(groupFrameworkHits(frameworkHits));
	// Persist new/refreshed entries. meta.fetchedAt is NOT touched here: fetchEndoflife stamps
	// it on a successful fetch only, so an offline run never makes the cache look fresh.
	if (!injected) saveJsonCache(EOL_CACHE_PATH, cache);
	return results;
}

/**
 * Collapse EOL hits that share a product AND a cycle into one finding per manifest.
 *
 * The Composer path groups by a curated framework registry; everywhere else the endoflife.date
 * PRODUCT is already the grouping key, so no registry is needed. Measured on a 105-module
 * Spring reactor: 16 rows carrying 5 distinct verdicts, 13 of them restating "this app runs
 * Spring 4.3" and "…Spring Boot 1.5". One fact, one fix — bump the BOM — and nine copies of it
 * bury Jetty, Tomcat and Hibernate, which are separate findings.
 *
 * Cycle is part of the key on purpose: components that disagree about a cycle produce one
 * finding each, never a merged and possibly wrong one.
 */
function groupEolByProduct(hits) {
	if (!hits || !hits.length) return [];
	const coord = d => `${d.groupId || d.namespace || ""}:${d.artifactId || d.name || ""}`;
	// Keyed on (product, cycle) and deliberately NOT on the manifest. The Composer grouping
	// keys per lockfile because a PHP app has one; a 105-module Maven reactor has 105 poms, so
	// keying per manifest reproduces the very duplication this exists to remove — measured, it
	// turned 4 distinct verdicts into 26 rows. "This project runs Spring 4.3" is one fact no
	// matter how many modules declare it; every manifest is kept on the anchor below.
	const groups = new Map();
	for (const h of hits) {
		const key = `${h.product}|${h.cycle}`;
		let g = groups.get(key);
		if (!g) { g = { paths: new Set(), hits: [] }; groups.set(key, g); }
		for (const mp of h.dep.manifestPaths || []) g.paths.add(mp);
		g.hits.push(h);
	}
	const out = [];
	for (const g of groups.values()) {
		// A group of one is not a group. Pass the hit through untouched so the record keeps its
		// identity (other findings hold the same object) and no spurious component list appears.
		if (g.hits.length === 1) { out.push(g.hits[0]); continue; }
		const byCoord = new Map(g.hits.map(h => [coord(h.dep), h]));
		const names = [...byCoord.keys()].sort();
		// The anchor is what an auditor would actually bump: a BOM pins the whole train, so it
		// wins; failing that a declared dependency beats a transitive one (you cannot bump what
		// you do not declare); then alphabetical, so a re-run picks the same one.
		const score = n => {
			const h = byCoord.get(n);
			return (/-bom$/.test(n) ? 0 : 2) + (h.dep.scope === "transitive" ? 1 : 0);
		};
		const anchor = [...names].sort((a, b) => score(a) - score(b) || a.localeCompare(b))[0];
		const anchorHit = byCoord.get(anchor);
		const components = names.map(n => ({ name: n, version: byCoord.get(n).dep.version }));
		let dep = anchorHit.dep;
		if (g.paths.size) {
			// Clone, never mutate: other findings hold the same record. pomPaths must stay the
			// SAME array object as manifestPaths (repo convention). Every manifest that declares
			// the product is kept, so nothing is lost by collapsing the rows.
			const mp = [...g.paths].sort();
			dep = { ...anchorHit.dep, manifestPaths: mp, pomPaths: mp };
		}
		out.push({ ...anchorHit, dep, anchor, components });
	}
	return out;
}

function composerFullName(dep) {
	return `${dep.namespace || dep.groupId || ""}/${dep.name || dep.artifactId}`.toLowerCase();
}

/**
 * Collapse framework-component hits into ONE finding per (framework, manifest, cycle).
 *
 * 51 symfony/* packages at 5.4.x are one fact — "this app runs Symfony 5.4" — not 51 rows.
 * The finding's `dep` is the ANCHOR's record (first of the framework's declared anchors
 * present, else the first component alphabetically), cloned and narrowed to the group's
 * manifest so the report's "defined in" footer points at the right lockfile. Every
 * component is kept in `components[]` (JSON stays exhaustive).
 *
 * Grouping by cycle is the coherence self-check: components that disagree on a cycle
 * produce one finding per cycle — never a merged, possibly wrong one.
 */
function groupFrameworkHits(hits) {
	if (!hits.length) return [];
	const groups = new Map();
	for (const h of hits) {
		const paths = (h.dep.manifestPaths && h.dep.manifestPaths.length) ? h.dep.manifestPaths : [""];
		for (const manifestPath of paths) {
			const key = `${h.frameworkId}|${manifestPath}|${h.cycle}`;
			let g = groups.get(key);
			if (!g) { g = { manifestPath, hits: [] }; groups.set(key, g); }
			g.hits.push(h);
		}
	}
	const out = [];
	for (const g of groups.values()) {
		const fw = COMPOSER_FRAMEWORKS[g.hits[0].frameworkId] || {};
		const byName = new Map(g.hits.map(h => [composerFullName(h.dep), h]));
		const names = [...byName.keys()].sort();
		const anchor = (fw.anchors || []).find(a => byName.has(a)) || names[0];
		const anchorHit = byName.get(anchor);
		const components = names.map(n => ({ name: n, version: byName.get(n).dep.version }));
		let dep = anchorHit.dep;
		if (g.manifestPath) {
			// Clone, never mutate: other findings/matches hold the same record. pomPaths must
			// stay the SAME array object as manifestPaths (repo convention).
			const mp = [g.manifestPath];
			dep = { ...anchorHit.dep, manifestPaths: mp, pomPaths: mp };
		}
		out.push({ ...anchorHit, dep, anchor, components });
	}
	return out;
}

// -------- Obsolete via curated list --------

function checkObsoleteDeps(resolvedDeps) {
	const results = [];
	const seen = new Set();
	for (const dep of resolvedDeps.values()) {
		const key = `${dep.groupId}:${dep.artifactId}`;
		if (seen.has(key)) continue;
		const entry = KNOWN_OBSOLETE[key];
		if (!entry) continue;
		seen.add(key);
		results.push({
			dep,
			severity: entry.severity || "MEDIUM",
			replacement: entry.replacement || null,
			reason: entry.reason || "",
		});
	}
	return results;
}

function checkObsolete(dep) {
	const entry = KNOWN_OBSOLETE[`${dep.groupId}:${dep.artifactId}`];
	return entry ? { dep, ...entry } : null;
}

// -------- Outdated via Maven Central --------

/** Every <version> in a maven-metadata.xml body, in document order. */
function parseMavenMetadataVersions(xml) {
	if (!xml) return [];
	return [...xml.matchAll(/<version>([^<]+)<\/version>/g)].map(m => m[1].trim()).filter(Boolean);
}

/**
 * Publication date of one version, from the POM's Last-Modified header. maven-metadata.xml
 * only carries an artifact-level <lastUpdated>, so the date has to come from the file itself;
 * a HEAD costs no body and hits the same CDN rotation. Measured against Solr's timestamps on
 * 25 coordinates: 20 exact, 22 within two days, the rest old artifacts whose storage was
 * touched after publication. Best-effort — a null date just leaves the column empty.
 */
async function pomLastModified(repos, groupId, artifactId, version, opts = {}) {
	try {
		const { tryRepos } = require("./maven-repo");
		const p = `${groupId.replace(/\./g, "/")}/${artifactId}/${version}/${artifactId}-${version}.pom`;
		const hit = await tryRepos(repos, p, {
			method: "HEAD", key: `${groupId}:${artifactId}`, health: opts.health,
			userAgent: "fad-checker-outdated-checker",
		});
		const lm = hit?.response?.headers?.get?.("last-modified");
		if (!lm) return null;
		const d = new Date(lm);
		return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
	} catch { return null; }
}

/**
 * Latest published version of a coordinate.
 *
 * maven-metadata.xml over the repository rotation comes FIRST. It is a static file on the
 * CDN, spread across Central plus the officially listed mirrors, and it reaches private
 * repositories too. Measured on 165 real coordinates from a 105-module reactor:
 * metadata answered 165/165 in 7.6 s, Solr answered 82/165 in 222 s — and Solr's index was
 * STALE on 92 of them, every single disagreement in the same direction (it reported
 * logback-classic 1.5.18 when 1.6.3 was published, netty-all 4.2.1.Final against 4.2.18.Final).
 * So this is a correctness fix that happens to be 29× faster, not an optimisation.
 *
 * Solr remains the fallback: it still answers for coordinates whose metadata cannot be read,
 * and it carries a publication timestamp of its own.
 */
async function fetchLatestVersion(groupId, artifactId, cache, opts = {}) {
	const key = `${groupId}:${artifactId}`;
	if (cache.entries[key]) return cache.entries[key];
	if (opts.offline) return null;

	if (Array.isArray(opts.repos) && opts.repos.length) {
		try {
			const { fetchMavenMetadata } = require("./maven-repo");
			const hit = await fetchMavenMetadata(opts.repos, groupId, artifactId, {
				userAgent: "fad-checker-outdated-checker", health: opts.health,
			});
			if (hit?.body) {
				// <release> is "latest non-SNAPSHOT" and will happily name a beta, so pick the
				// highest STABLE version instead — unless the dep is already on a pre-release.
				const latest = latestStableVersion(parseMavenMetadataVersions(hit.body), { current: opts.currentVersion })
					|| parseMavenMetadataLatest(hit.body);
				if (latest) {
					const entry = {
						latest,
						releaseDate: await pomLastModified(opts.repos, groupId, artifactId, latest, opts),
						source: hit.repo.name || hit.repo.url,
					};
					cache.entries[key] = entry;
					return entry;
				}
			}
		} catch { /* fall through to Solr */ }
	}

	try {
		const url = `https://search.maven.org/solrsearch/select?q=g:%22${encodeURIComponent(groupId)}%22+AND+a:%22${encodeURIComponent(artifactId)}%22&core=gav&rows=1&wt=json`;
		const res = await fetch(url, { headers: { "User-Agent": "fad-checker-outdated-checker" } });
		if (res.ok) {
			const doc = (await res.json())?.response?.docs?.[0];
			if (doc) {
				const entry = { latest: doc.v, releaseDate: doc.timestamp ? new Date(doc.timestamp).toISOString().slice(0, 10) : null, source: "central-solr" };
				cache.entries[key] = entry;
				return entry;
			}
		}
	} catch { /* nothing left to try */ }

	cache.entries[key] = { error: "not found" };
	return cache.entries[key];
}

/**
 * Pull the "latest" version from a maven-metadata.xml body. Prefers
 * <versioning><release> (stable), falls back to <versioning><latest> and
 * then the highest entry in <versioning><versions>.
 */
function parseMavenMetadataLatest(xml) {
	if (!xml) return null;
	const release = xml.match(/<release>([^<]+)<\/release>/);
	if (release?.[1]) return release[1].trim();
	const latest = xml.match(/<latest>([^<]+)<\/latest>/);
	if (latest?.[1]) return latest[1].trim();
	const versions = [...xml.matchAll(/<version>([^<]+)<\/version>/g)].map(m => m[1].trim()).filter(Boolean);
	if (versions.length) {
		try { versions.sort((a, b) => compareMavenVersions(a, b)); return versions[versions.length - 1]; }
		catch { return versions[versions.length - 1]; }
	}
	return null;
}

async function checkOutdatedDeps(resolvedDeps, opts = {}) {
	const { verbose, offline, concurrency = 8, repos, onProgress } = opts;
	const cache = loadJsonCache(VERSION_CACHE_PATH);
	const fresh = cache.meta?.fetchedAt && (Date.now() - cache.meta.fetchedAt) < VERSION_CACHE_MAX_AGE_MS;
	if (!fresh && !offline) cache.entries = {};
	// Maven Central only — npm/composer/pypi/nuget have their own registries (codec.checkRegistry).
	// Transitives are excluded BEFORE fetching: the Outdated chapter only reports deps you
	// declare and can bump (fad-checker.js drops transitive rows after the fact anyway), and
	// on a real reactor transitives outnumber directs 5-10× — querying Central for versions
	// that never reach the report was where most of this pass's wall-clock went.
	const list = [...resolvedDeps.values()].filter(d =>
		d.version && !/\$\{|SNAPSHOT/i.test(d.version) && d.ecosystem === "maven" && d.scope !== "transitive");
	const results = [];

	// Progress indicator — Maven Central can serve hundreds of deps in a few
	// seconds with 8-way concurrency, but on first run (cold cache) the user
	// would see total silence for 20-60s.
	const liveCount = offline ? 0 : list.filter(d => !cache.entries[`${d.groupId}:${d.artifactId}`]).length;
	if (liveCount && !offline && !onProgress) {
		console.log(`📅 Outdated: checking ${list.length} deps against Maven Central (${liveCount} live, ${list.length - liveCount} cached)…`);
	}

	let cursor = 0;
	let processed = 0;
	const startedAt = Date.now();
	const printOutdatedProgress = (final = false) => {
		if (onProgress) { onProgress(processed, list.length); return; }
		if (!liveCount) return;
		const elapsed = Math.round((Date.now() - startedAt) / 1000);
		const pct = Math.round((processed / list.length) * 100);
		const line = `   outdated: ${processed}/${list.length} (${pct}%) — ${elapsed}s`;
		if (process.stdout.isTTY) process.stdout.write(`\r${line}${final ? "\n" : "          "}`);
		else if (final) console.log(line);
	};
	const workers = Array.from({ length: concurrency }, async () => {
		while (cursor < list.length) {
			const dep = list[cursor++];
			const entry = await fetchLatestVersion(dep.groupId, dep.artifactId, cache, { offline, repos, currentVersion: dep.version });
			processed++;
			if (processed % 10 === 0 || processed === list.length) printOutdatedProgress();
			if (!entry?.latest) continue;
			try {
				if (compareMavenVersions(dep.version, entry.latest) < 0) {
					results.push({ dep, latest: entry.latest, releaseDate: entry.releaseDate || null });
					if (verbose) process.stdout.write(`  outdated: ${dep.groupId}:${dep.artifactId} ${dep.version} → ${entry.latest}\n`);
				}
			} catch { /* ignore comparison failure */ }
		}
	});
	await Promise.all(workers);
	if (liveCount) printOutdatedProgress(true);

	cache.meta = { fetchedAt: Date.now() };
	saveJsonCache(VERSION_CACHE_PATH, cache);
	results.sort((a, b) => `${a.dep.groupId}:${a.dep.artifactId}`.localeCompare(`${b.dep.groupId}:${b.dep.artifactId}`));
	return results;
}

module.exports = {
	groupEolByProduct,
	checkEolDeps,
	getEolCycles,
	checkObsoleteDeps,
	checkObsolete,
	checkOutdatedDeps,
	findEolProduct,
	findCycleForVersion,
	isEol,
	lifecycleStatus,
	isEolCacheFresh,
	fetchEndoflife,
	normalizeEolCache,
	EOL_CACHE_MAX_AGE_MS,
	EOL_MAPPING,
	COMPOSER_FRAMEWORKS,
	EOL_CACHE_PATH,
	KNOWN_OBSOLETE,
	loadJsonCache,
	saveJsonCache,
	CACHE_DIR,
};
